- name: 'Change file permission'
  hosts: client1
  become: true
  ignore_errors: yes
  tasks:
    - name: check file service
      shell: systemctl status auditd | grep Active | awk '{ print $2 }'
      register: auditdstatus
    - debug: var=auditdstatus
    - name: Kill auditd failed pid
      shell: for i in `auditctl -s | grep -i pid | awk '{ print $2 }'`; do kill -9 $i; done
      when: auditdstatus.stdout_lines == [ "active" ]
    - name: Start auditd service
      service:
        name: auditd
        state: started
