- name: 'Change file permission'
  hosts: client1
  become: true
  ignore_errors: yes
  tasks:
    - name: check file service
      shell: systemctl status auditd | grep Active | awk '{ print $2 }'
      register: auditdstatus
    - debug: var=auditdstatus
    - name: check pid using tanium
      shell: for i in `auditctl -s | grep -i pid | awk '{ print $2 }'`; do ps -ef |grep $i|grep auditd|awk '{ print $8 }'; done
      register: taniumpid
    - debug: var=taniumpid
    - name: Kill auditd failed pid
      shell: for i in `auditctl -s | grep -i pid | awk '{ print $2 }'`; do kill -9 $i; done
      when: 
        - auditdstatus.stdout_lines == [ "active" ] and taniumpid.stdout_lines == [ "/sbin/auditd" ]
        - ansible_distribution == "CentOS"
        - ansible_distribution_major_version == "7" or ansible_distribution_major_version == "6"
    - name: Start auditd service
      service:
        name: auditd
        state: started
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7" or ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"
