- name: 'Accessing the facts inside the playbook'

  # Target: where our play will run and options it will run with
  hosts: client
  gather_facts: true

  # Task: the list of tasks that will be executed within the playbook
  tasks:
     - name: Show IP Address
       debug:
         msg: "{{ ansible_default_ipv4.address }}"
