---
- name: Install IIS
  hosts: win
  gather_facts: true
  tasks:
   - win_package:
       path: C:\Program Files\7-Zip\Uninstall.exe
       product_id: 7-Zip
       arguments: /S
       state: absent